repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      files: \.(py|pyx|sh|md|txt|in|ini|json|yaml|yml)$
    - id: end-of-file-fixer
      files: \.(py|pyx|sh|md|txt|in|ini|json|yaml|yml)$
    - id: fix-byte-order-marker
      files: \.(py|pyx)$
    - id: check-added-large-files
      args:
        - '--maxkb=2000'
    - id: check-docstring-first
      files: \.(py|pyx)$
    - id: fix-encoding-pragma
      files: \.(py|pyx)$
      args:
        - '--remove'
    - id: mixed-line-ending
      args:
        - '--fix=no'
    - id: check-executables-have-shebangs
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-json
    - id: check-yaml
    - id: debug-statements
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      args:
        - '--max-line-length=119'
        - '--ignore=E203,E231,W503,W504'
